<?php

namespace App\Domain;

abstract class BaseData
{
    public static function getData() {
        return [
            [
                'title' => 'Électricité',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/high-voltage_26a1.png',
                'subtitle' => 'Les principaux graphs sur l\'électricité',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],                            [
                                'title' => 'Répartition du mix énergétique Français par source',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/explore/embed/dataset/eco2mix-national-cons-def/analyze/?disjunctive.nature&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoiZmlvdWwiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjOGRhMGNiIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImNoYXJib24iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNTQ1NDU0In0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6ImdheiIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNlNWM0OTQifSx7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoibnVjbGVhaXJlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2E2ZDg1NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJlb2xpZW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6InNvbGFpcmUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjZmZkOTJmIn0seyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoibGluZSIsImZ1bmMiOiJTVU0iLCJ5QXhpcyI6Imh5ZHJhdWxpcXVlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2U1YzQ5NCJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJwb21wYWdlIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI2IzYjNiMyJ9LHsiYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJiaW9lbmVyZ2llcyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9oZXVyZSIsIm1heHBvaW50cyI6MTAwLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZWNvMm1peC1uYXRpb25hbC1jb25zLWRlZiIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUubmF0dXJlIjp0cnVlfX0sInNlcmllc0JyZWFrZG93biI6IiIsInNlcmllc0JyZWFrZG93blRpbWVzY2FsZSI6IiJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwic2luZ2xlQXhpcyI6dHJ1ZX0%3D&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Panneau solaire',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/sun_2600-fe0f.png',
                'subtitle' => 'Les principaux graphs sur le panneau solaire',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Éolien',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/wind-face_1f32c-fe0f.png',
                'subtitle' => 'Les principaux graphs sur l\'éolien',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Gaz',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/dashing-away_1f4a8.png',
                'subtitle' => 'Les principaux graphs sur le gaz',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Pétrole',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/fuel-pump_26fd.png',
                'subtitle' => 'Les principaux graphs sur le pétrole',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Gaz',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/dashing-away_1f4a8.png',
                'subtitle' => 'Les principaux graphs sur le gaz',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Charbon',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/rock_1faa8.png',
                'subtitle' => 'Les principaux graphs sur le charbon',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ],
            [
                'title' => 'Biométhane',
                'emoji' => 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/cow_1f404.png',
                'subtitle' => 'Les principaux graphs sur le biométhane',
                'subcategory' => [
                    [
                        'title' => '',
                        'graphs' => [
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ],
                            [
                                'title' => 'Production horaire et provisoire de biométhane des sites d\'injection raccordés au réseau de transport',
                                'iframe' => '<iframe src="https://opendata.reseaux-energies.fr/chart/embed/?dataChart=eyJ0aW1lc2NhbGUiOiJkYXkiLCJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IlNVTSIsInlBeGlzIjoicHJvZF9qb3VybmFsaWVyZV9td2hfcGNzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoicmFuZ2UtQWNjZW50In1dLCJ4QXhpcyI6ImpvdXJuZWVfZ2F6aWVyZSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6InllYXIiLCJzb3J0IjoiIiwic2VyaWVzQnJlYWtkb3duIjoib3BlcmF0ZXVyIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwcm9kdWN0aW9uLW5hdGlvbmFsZS1ob3JhaXJlLWRlLWdhei1kb25uZWVzLXByb3Zpc29pcmVzIiwib3B0aW9ucyI6e319fV0sImFsaWduTW9udGgiOnRydWUsImRpc3BsYXlMZWdlbmQiOnRydWV9&static=false&datasetcard=false" width="400" height="300" frameborder="0"></iframe>'
                            ]
                        ]
                    ]
                ]
            ]
        ];
    }
}